parameters:
- name: entornos
  type: string
  default: UAT
  values:
  - UAT
  - STG
- name: N° Iteraciones
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5
- name: myBoolean
  type: boolean
  default: true
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
    nested:
      one: apple
      two: pear
      count: 3
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two

trigger: none

jobs: 
- job: Install Newman-Reporter-htmlextra
  steps: 'sudo npm install -g newman-reporter-htmlextra'


jobs:
- ${{ if contains(parameters.entornos, 'UAT') }}:
  - job: Ruta 1
    steps:
    - script: echo Building x86...
- ${{ if contains(parameters.entornos, 'STG') }}:
  - job: Ruta 2
    steps:
    - script: echo Building x64...
- ${{ if contains(parameters.entornos, '') }}:
  - job: Ruta 3
    steps:
    - script: echo Nada...