trigger: none

parameters:
    - name: entorno
      type: string
      default: UAT
      values:
            - UAT 
            - STG 
    - name: iteraciones
      type: number
      default: 2
      values:
            - 1 
            - 2 
            - 3 
            - 4 
            - 5
    - name: data
      type: string
      default: TD
      values:
            - CU 
            - TC 
            - TD




jobs:
      - job: Ejecucion_en_${{ parameters.entorno }}
        pool:
            vmImage: ubuntu-latest
        steps:
            - template: template_${{ parameters.entorno }}.yml 
              parameters:
                it: ${{ parameters.iteraciones }}
                dat: ${{ parameters.data }}
            - script: echo step one 









