resources:
  repositories:
  - repository: Test Runner
    type: git
    name: GiruBack/Test Runner
    ref: main

variables:
  tools.ref: $[ resources.repositories['Test Runner'].ref ]

parameters:
- name: entorno
  type: string
  default: UAT
  values:
  - UAT
  - STG
- name: iteraciones
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5

trigger: none


steps:
#checkout referenced repository
  - checkout: Test Runner
#List SourcesDirectory files
- bash: |
    echo "Tools version: $TOOLS_REF"
