parameters:
- name: entorno
  type: string
  default: UAT
  values:
  - UAT
  - STG
- name: iteraciones
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5
- name: myBoolean
  type: boolean
  default: true
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
    nested:
      one: apple
      two: pear
      count: 3
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two

trigger: none


jobs: 
- ${{ if contains(parameters.entorno, 'UAT') }}:
  - job: Ruta1
    steps:
    - script: echo Building ${{ parameters.entorno }}...${{ parameters.iteraciones }}
- ${{ if contains(parameters.entorno, 'STG') }}:
  - job: Ruta2
    steps:
    - script: echo Building ${{ parameters.entorno }}...${{ parameters.iteraciones }}
- ${{ if contains(parameters.entorno, ' ') }}:
  - job: Ruta3
    steps:
    - script: echo Nada...