resources:
  repositories:
  - repository: Test1
    type: git
    name: Giru Back/Test1
    ref: master




parameters:
- name: entorno
  type: string
  default: UAT
  values:
  - UAT
  - STG
- name: iteraciones
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5

trigger: none



jobs: 
-job: ReadFile
steps:
#checkout referenced repository
  - checkout: test
#List SourcesDirectory files
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls ''$(Build.SourcesDirectory)'''
      
- ${{ if contains(parameters.entorno, 'UAT') }}:
  - job: Ruta1
    steps:
    - script: echo Building ${{ parameters.entorno }}...${{ parameters.iteraciones }}
- ${{ if contains(parameters.entorno, 'STG') }}:
  - job: Ruta2
    steps:
    - script: echo Building ${{ parameters.entorno }}...${{ parameters.iteraciones }}
- ${{ if contains(parameters.entorno, ' ') }}:
  - job: Ruta3
    steps:
    - script: echo Nada...
