trigger: none

parameters:
    - name: entorno
      type: string
      default: UAT
      values:
            - UAT 
            - STG 
    - name: iteraciones
      type: number
      default: 2
      values:
            - 1 
            - 2 
            - 3 
            - 4 
            - 5

pool:
  vmImage: ubuntu-latest

jobs:
    - ${{ if contains(parameters.entorno, 'UAT') }}:
      - job: Ejecucion_en_UAT
        steps:
            - template: templateUat.yml 
            - script: echo step one 
            
    - ${{ if contains(parameters.entorno, 'STG') }}:
      - job: Ejecucion_en_STG
        steps:
            - template: templateStg.yml 
            - script: echo step two