resources:
  repositories:
  - repository: Test1
    type: git
    name: GiruBack/Test1
    ref: master
    - repository: Test Runner
    type: git
    name: GiruBack/Test Runner
    ref: master





parameters:
- name: entorno
  type: string
  default: UAT
  values:
  - UAT
  - STG
- name: iteraciones
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5

trigger: none


steps:
#checkout referenced repository
  - checkout: test
#List SourcesDirectory files
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls ''$(Build.SourcesDirectory)'''
