trigger: none

parameters:
    - name: entorno
      type: string
      default: UAT
      values:
            - UAT 
            - STG 
    - name: iteraciones
      type: number
      default: 2
      values:
            - 1 
            - 2 
            - 3 
            - 4 
            - 5
    - name: data
      type: string
      default: CU
      values:
            - CU 
            - TC 
            - TD

pool:
  vmImage: ubuntu-latest

jobs:
    parameters:
      it: ${{ parameters.iteraciones }}
      dat: ${{ parameters.data }}
    - ${{ if contains(parameters.entorno, 'UAT') }}:
      - job: Ejecucion_en_UAT
        steps:
            - template: templateUat.yml 
              parameters:
                it: ${{ parameters.iteraciones }}
            - script: echo step one 
            
    - ${{ if contains(parameters.entorno, 'STG') }}:
      - job: Ejecucion_en_STG
        steps:
            - template: templateStg.yml 
              parameters:
                it: ${{ parameters.iteraciones }}
            - script: echo step two








